# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, url, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   url = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[subnavigation]]
  identifier = "Team"
  name = "Team"
  url = "team"
  weight = 1

[[main]]
  identifier = "Winnings"
  name = "Winnings"
  pageref = "winings"
  weight = 2

[[main]]
  name = "Skills"
  identifier = "Skills"
  pageref = "skills"
  weight = 3

#[[main]]
#  name = "example sub-menu 2"
#  parent = "Parent"
#  url = "posts"
#  weight = 20

#[[subnavigation]]
#  name = "An interesting topic"
#  
#  weight = 10

#[[subnavigation]]
#  name = "My Awesome Category"
#  pre = "github"
#  url = "categories/awesome"
#  weight = 20

#[[main]]
#  name = "Categories"
#  url = "categories"
#  weight = 20

#[[main]]
#  name = "Tags"
#  url = "tags"
#  weight = 30


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


[[footer]]
  identifier = "instagram"
  name = "instagram"
  url = "https://www.instagram.com/00ha.rish00?igsh=aWhtd3F6MWprM3k="
  weight = 1
[[footer]]
  identifier = "twitter"
  name = "twitter"
  url = "https://x.com/0just_an_guy0?t=AmJgahFJ73H3BYo0BtACdw&s=09"
  weight = 2
[[footer]]
  name = "github"
  identifier = "github"
  url = "https://github.com/harish-pushan"
  weight = 3
  
  